pipelines:
  branches:
    main:
      - step:
          name: Build and test the app
          image: node:18-alpine # Updated to Node.js 18
          script:
            - if ! command -v yarn >/dev/null 2>&1; then npm install -g yarn; fi # Check if yarn is installed
            - yarn install
            - yarn build

  pull-requests:
    '**':
      - step:
          name: 'Lint'
          caches:
            - node
          image: node:18-alpine # Updated to Node.js 18
          script:
            - if ! command -v yarn >/dev/null 2>&1; then npm install -g yarn; fi # Check if yarn is installed
            - yarn install

  custom:
    production: 
      - step:
          name: Building the app
          image: node:18-alpine # Updated to Node.js 18
          script:
            - if ! command -v yarn >/dev/null 2>&1; then npm install -g yarn; fi # Check if yarn is installed
            - yarn install
            - yarn build
          artifacts:
            - build/**
      - step:
          name: Deploying the app to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                LOCAL_PATH: "build"
